### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Kea172** [Kea172/Kea172.github.io#1]
- [ ] Centre column page layout
- [ ] give everything a bit more polish
- [ ] better site icon
- [ ] standard page layout?
- [ ] docs subsection
- [ ] formatting
- [ ] Improve CSS
- [ ] other shit idk
